### ISSUE TITLE
how are you sir?

### ISSUE THREAD

**Issue by NamasteIndia** [Agamya-Samuel/c_programs#1]
Long Time no see

**Comment by Agamya-Samuel** [comment]
> Long Time no see

Yes, sir i'm good How are you, Github Issues bhi nhi chora 😂

**Comment by NamasteIndia** [comment]
Sir I m from billage area that's why! 😆

**Comment by Agamya-Samuel** [comment]
> Sir I m from billage area that's why! 😆

Sir how do you do...

**Comment by NamasteIndia** [comment]
Not very well sir getting diagnosed for gastritis
